package fault

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/RichardZ-code/http-fault-injection-proxy/internal/config"
)

func configured(t *testing.T, text string) *Engine {
	t.Helper()
	p := filepath.Join(t.TempDir(), "scenario.yaml")
	if err := os.WriteFile(p, []byte(text), 0600); err != nil {
		t.Fatal(err)
	}
	c, err := config.Load(p)
	if err != nil {
		t.Fatal(err)
	}
	e, err := New(c)
	if err != nil {
		t.Fatal(err)
	}
	return e
}

func allocate(t *testing.T, e *Engine, method, path string) Decision {
	t.Helper()
	d, err := e.Allocate(context.Background(), method, path)
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func TestMatchingAndCounters(t *testing.T) {
	text := `version: 1
rules:
  - {id: first, method: GET, path_prefix: /api, faults: {every_nth_request: 3, status: 503}}
  - {id: second, path_prefix: /api/, faults: {every_nth_request: 1, status: 500}}
  - {id: delay, path_prefix: /wait, faults: {delay_ms: 1}}
`
	e := configured(t, text)
	for i := 1; i <= 30; i++ {
		d := allocate(t, e, "GET", "/apix")
		want := 0
		if i%3 == 0 {
			want = 503
		}
		if d.RuleID != "first" || d.Sequence != uint64(i) || d.Status != want {
			t.Fatal(d)
		}
	}
	d := allocate(t, e, "POST", "/api/x")
	if d.RuleID != "second" || d.Sequence != 1 || d.Status != 500 {
		t.Fatal(d)
	}
	for _, p := range []string{"/API", "/else", "/api%2Fx"} {
		// The engine does not decode literal input; POST requires /api/ here.
		d := allocate(t, e, "POST", p)
		if d.RuleID != "none" {
			t.Fatal(d)
		}
	}
	if d := allocate(t, e, "TRACE", "/wait"); d.RuleID != "none" {
		t.Fatal(d)
	}
	for i := 1; i <= 2; i++ {
		if d := allocate(t, e, "HEAD", "/wait"); d.Sequence != uint64(i) || d.Status != 0 || d.Delay == 0 {
			t.Fatal(d)
		}
	}
	if d := allocate(t, configured(t, text), "GET", "/api"); d.Sequence != 1 || d.Status != 0 {
		t.Fatal("reset", d)
	}
}

func TestSeededFixturesAndIsolation(t *testing.T) {
	// Independently calculated using SHA-256 plus the installed Go 1.27.1
	// PCG 128-bit recurrence/DXSM and Float64's low 53 bits, in Python integer
	// arithmetic. No values are generated by Engine in the expectation path.
	for _, tc := range []struct {
		seed uint64
		want string
	}{{42, "11110011101110111111"}, {99, "01000000001111011110"}} {
		text := fmt.Sprintf(`version: 1
seed: %d
rules:
  - {id: other, path_prefix: /other, faults: {probability: 0.5, status: 500}}
  - {id: coin, path_prefix: /coin, faults: {probability: 0.5, status: 503}}
`, tc.seed)
		for repeat := 0; repeat < 2; repeat++ {
			e := configured(t, text)
			var got strings.Builder
			for i := 0; i < len(tc.want); i++ {
				allocate(t, e, "GET", "/other")
				d := allocate(t, e, "GET", "/coin")
				if d.Sequence != uint64(i+1) {
					t.Fatal(d)
				}
				if d.Status == 503 {
					got.WriteByte('1')
				} else {
					got.WriteByte('0')
				}
			}
			if got.String() != tc.want {
				t.Fatalf("seed=%d repeat=%d got=%s want=%s", tc.seed, repeat, got.String(), tc.want)
			}
			t.Logf("seed=%d repeat=%d selected=%s", tc.seed, repeat, got.String())
		}
	}
	// Identity determines seeds, not order: coin has the same fixture by itself.
	e := configured(t, "version: 1\nrules: [{id: coin, path_prefix: /coin, faults: {probability: 0.5, status: 503}}]")
	for _, b := range "11110011101110111111" {
		d := allocate(t, e, "GET", "/coin")
		if (d.Status != 0) != (b == '1') {
			t.Fatal("list-index seeding", d)
		}
	}
}

func TestProbabilityBoundariesConsumeDraws(t *testing.T) {
	for _, p := range []int{0, 1} {
		e := configured(t, fmt.Sprintf("version: 1\nrules: [{id: coin, path_prefix: /, faults: {probability: %d, status: 503}}]", p))
		reference := configured(t, "version: 1\nrules: [{id: coin, path_prefix: /, faults: {probability: 0.5, status: 503}}]")
		for i := 0; i < 8; i++ {
			d := allocate(t, e, "GET", "/")
			if (d.Status == 503) != (p == 1) {
				t.Fatal(d)
			}
			allocate(t, reference, "GET", "/")
		}
		if got, want := e.rules[0].rng.Float64(), reference.rules[0].rng.Float64(); got != want {
			t.Fatalf("boundary omitted draws: %v %v", got, want)
		}
	}
}

func TestCancellationAndExhaustion(t *testing.T) {
	e := configured(t, "version: 1\nrules: [{id: coin, path_prefix: /, faults: {probability: 0.5, status: 503}}]")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := e.Allocate(ctx, "GET", "/"); !errors.Is(err, context.Canceled) || e.rules[0].sequence != 0 {
		t.Fatal("cancelled allocation", err)
	}
	if d := allocate(t, e, "GET", "/"); d.Sequence != 1 || d.Status != 503 {
		t.Fatal(d)
	}
	e.rules[0].sequence = ^uint64(0) - 1
	if d := allocate(t, e, "GET", "/"); d.Sequence != ^uint64(0) {
		t.Fatal(d)
	}
	reference := configured(t, "version: 1\nrules: [{id: coin, path_prefix: /, faults: {probability: 0.5, status: 503}}]")
	allocate(t, reference, "GET", "/")
	allocate(t, reference, "GET", "/")
	if d, err := e.Allocate(context.Background(), "GET", "/"); !errors.Is(err, ErrExhausted) || d.Sequence != 0 || d.Status != 0 || e.rules[0].sequence != ^uint64(0) {
		t.Fatal("exhaustion", d, err)
	}
	if e.rules[0].rng.Float64() != reference.rules[0].rng.Float64() {
		t.Fatal("exhaustion drew RNG")
	}
}

func TestConcurrentExactDecisions(t *testing.T) {
	e := configured(t, "version: 1\nrules: [{id: fifth, path_prefix: /, faults: {every_nth_request: 5, status: 503}}]")
	results := make(chan Decision, 1000)
	errs := make(chan error, 1000)
	var wg sync.WaitGroup
	for worker := 0; worker < 20; worker++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := 0; i < 50; i++ {
				d, err := e.Allocate(context.Background(), "GET", "/")
				results <- d
				errs <- err
			}
		}()
	}
	wg.Wait()
	close(results)
	close(errs)
	for err := range errs {
		if err != nil {
			t.Error(err)
		}
	}
	seen := map[uint64]bool{}
	selected := 0
	for d := range results {
		if seen[d.Sequence] || d.Sequence < 1 || d.Sequence > 1000 {
			t.Fatal("lost/duplicate sequence", d)
		}
		seen[d.Sequence] = true
		if d.Status == 503 {
			selected++
		}
	}
	if len(seen) != 1000 || selected != 200 {
		t.Fatalf("sequences=%d selected=%d", len(seen), selected)
	}
}
